# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9c47599da4adb2d3ab3f4c3da86077a07733500f93625b13a8b713d5fc63b385188419ad780a1001e034786040511b6b9569dd1c134dc26171de8cf10453d5c

test:
  secret_key_base: 1d672b4872fa2b88d893a7c6e88d028fbeb2101913289bafdd4cdffea373077862941f1f554213a83119ee5166d9bef2366587cc69e0ba6635a68596d20b8457

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
