development:
  adapter: postgresql
  encoding: unicode
  database: new_octoshell_development
  username: dbuser_dev
  password: pass

test:
  adapter: postgresql
  encoding: unicode
  database: new_octoshell_test
  username: dbuser_dev
  password: pass

production:
  adapter: postgresql
  encoding: unicode
  database: new_octoshell
  username: dbuser
  password: pass
  pool: 10
  min_messages: warning
