development:
  adapter: postgresql
  encoding: unicode
  database: top52
  username: dbuser
  password: pass

test:
  adapter: postgresql
  encoding: unicode
  database: top52
  username: dbuser
  password: pass

production:
  adapter: postgresql
  encoding: unicode
  database: top52
  username: dbuser
  password: pass
  pool: 10
  min_messages: warning
